-- HYBRID — Exercise library SEED (deduplicated catalog).
-- Run in the Supabase SQL Editor AFTER reference/sql-exercise.sql (which creates
-- the "Exercise" table). Idempotent: re-running skips rows already present (by
-- slug). Populates 209 published custom exercises from
-- reference/exercise-catalog.md so they appear in the web Builder + "Add exercise".
--
-- Field notes:
--  • pattern  — the closest core movement pattern (drives fatigue). Isolation
--    lifts map to the nearest (curls→pull, extensions→push, crunches→core).
--  • muscles  — the coarse engine enum (quads/glutes/posterior/back/chest/
--    shoulders/triceps). NEVER leave this empty: the engines resolve a lift to
--    its muscle groups, so a row with no muscles contributes ZERO load to
--    fatigue, ACWR, injury risk, volume-by-muscle, landmarks and muscle records
--    — the tissue reads as untrained no matter how hard it was worked. Groups
--    the enum lacks map to their coarse home, exactly as core's ENGINE_GROUP
--    already does: biceps + forearms + traps -> back, calves + abs + obliques
--    -> posterior. A coarse attribution beats none. Pinned by
--    packages/core/src/engines/catalog-coverage.test.ts, which fails the build
--    if any row here is empty or unresolvable.
--  • category — the muscle-group heading (library grouping only).
--  • aliases  — folds a built-in / second spelling onto the primary name.

insert into "Exercise"
  ("slug", "name", "pattern", "muscles", "category", "equipment", "aliases", "kind", "status", "source")
values
  ('barbell-bench-press', 'Barbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['barbell']::text[], ARRAY['Bench Press']::text[], 'strength', 'published', 'custom'),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['dumbbell']::text[], ARRAY['DB Bench Press']::text[], 'strength', 'published', 'custom'),
  ('incline-dumbbell-bench-press', 'Incline Dumbbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-dumbbell-bench-press', 'Decline Dumbbell Bench Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-crossover', 'Cable Crossover', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-cable-fly', 'Incline Cable Fly', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['cable']::text[], ARRAY['Incline Cable Crossover']::text[], 'strength', 'published', 'custom'),
  ('dumbbell-flyes', 'Dumbbell Flyes', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-dumbbell-flyes', 'Decline Dumbbell Flyes', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('machine-chest-press', 'Machine Chest Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('pec-deck-fly', 'Pec Deck Fly', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('chest-dip', 'Chest Dip', 'push', ARRAY['chest','triceps']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-machine-press', 'Incline Machine Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-machine-press', 'Decline Machine Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-chest-press', 'Cable Chest Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hex-press', 'Hex Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-floor-press', 'Dumbbell Floor Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('landmine-chest-press', 'Landmine Chest Press', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['landmine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-cable-fly', 'Single-Arm Cable Fly', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('deficit-push-up', 'Deficit Push-up', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-push-up', 'Incline Push-up', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-push-up', 'Decline Push-up', 'push', ARRAY['chest','triceps','shoulders']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('weighted-dip', 'Weighted Dip', 'push', ARRAY['chest','triceps']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('svend-press', 'Svend Press', 'push', ARRAY['chest']::text[], 'Chest', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-deadlift', 'Barbell Deadlift', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], ARRAY['Deadlift']::text[], 'strength', 'published', 'custom'),
  ('sumo-deadlift', 'Sumo Deadlift', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('romanian-deadlift', 'Romanian Deadlift', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-row', 'Barbell Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('one-arm-dumbbell-row', 'One-Arm Dumbbell Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-cable-row', 'Seated Cable Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('t-bar-row', 'T-Bar Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['t-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('lat-pulldown', 'Lat Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('pull-up', 'Pull-up', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('chin-up', 'Chin-up', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('back-extension', 'Back Extension', 'hinge', ARRAY['posterior']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('deficit-barbell-deadlift', 'Deficit Barbell Deadlift', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('rack-pull', 'Rack Pull', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('snatch-grip-deadlift', 'Snatch-Grip Deadlift', 'hinge', ARRAY['posterior','back','glutes']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('meadows-row', 'Meadows Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('pendlay-row', 'Pendlay Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seal-row', 'Seal Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-dumbbell-row', 'Incline Dumbbell Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('kroc-row', 'Kroc Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('chest-supported-machine-row', 'Chest-Supported Machine Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hammer-strength-high-row', 'Hammer Strength High Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('neutral-grip-lat-pulldown', 'Neutral Grip Lat Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('underhand-lat-pulldown', 'Underhand Lat Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-cable-lat-pulldown', 'Single-Arm Cable Lat Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('v-bar-pulldown', 'V-Bar Pulldown', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('weighted-pull-up', 'Weighted Pull-up', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('rack-chins', 'Rack Chins', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('inverted-row', 'Inverted Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('kelso-row', 'Kelso Row', 'pull', ARRAY['back']::text[], 'Back', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('standing-overhead-press', 'Standing Overhead Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['bodyweight']::text[], ARRAY['Overhead Press']::text[], 'strength', 'published', 'custom'),
  ('seated-barbell-shoulder-press', 'Seated Barbell Shoulder Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-dumbbell-press', 'Seated Dumbbell Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['dumbbell']::text[], ARRAY['DB Overhead Press']::text[], 'strength', 'published', 'custom'),
  ('arnold-press', 'Arnold Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('front-plate-raise', 'Front Plate Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['plate']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-front-raise', 'Dumbbell Front Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-rear-delt-fly', 'Dumbbell Rear Delt Fly', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-rear-delt-row', 'Barbell Rear Delt Row', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('face-pull', 'Face Pull', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('behind-the-neck-overhead-press', 'Behind-the-Neck Overhead Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-scott-press', 'Dumbbell Scott Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-dumbbell-shoulder-press', 'Single-Arm Dumbbell Shoulder Press', 'push', ARRAY['shoulders','triceps']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-6-way-raise', 'Dumbbell 6-Way Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('behind-the-back-cable-lateral-raise', 'Behind-the-Back Cable Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-dumbbell-lateral-raise', 'Incline Dumbbell Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('chest-supported-dumbbell-lateral-raise', 'Chest-Supported Dumbbell Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-lu-raise', 'Dumbbell Lu Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-front-raise', 'Cable Front Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-dumbbell-front-raise', 'Incline Dumbbell Front Raise', 'push', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-bent-over-dumbbell-rear-delt-raise', 'Seated Bent-Over Dumbbell Rear Delt Raise', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-bench-rear-delt-fly', 'Incline Bench Rear Delt Fly', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-cable-rear-delt-fly', 'Single-Arm Cable Rear Delt Fly', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-face-pull-with-external-rotation', 'Cable Face Pull with External Rotation', 'pull', ARRAY['shoulders']::text[], 'Shoulders', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-shrug', 'Barbell Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('smith-machine-shrug', 'Smith Machine Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('behind-the-back-smith-machine-shrug', 'Behind-the-Back Smith Machine Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-shrug', 'Cable Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('kelso-shrug', 'Kelso Shrug', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('farmer-s-walk', 'Farmer''s Walk', 'carry', ARRAY['back','posterior']::text[], 'Traps & Forearms', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-wrist-curl', 'Barbell Wrist Curl', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('reverse-barbell-wrist-curl', 'Reverse Barbell Wrist Curl', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('reverse-dumbbell-wrist-curl', 'Reverse Dumbbell Wrist Curl', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('plate-pinch', 'Plate Pinch', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['plate']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('wrist-roller-rollup', 'Wrist Roller Rollup', 'pull', ARRAY['back']::text[], 'Traps & Forearms', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-back-squat', 'Barbell Back Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], ARRAY['Back Squat']::text[], 'strength', 'published', 'custom'),
  ('barbell-front-squat', 'Barbell Front Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], ARRAY['Front Squat']::text[], 'strength', 'published', 'custom'),
  ('hack-squat', 'Hack Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('leg-press', 'Leg Press', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-walking-lunge', 'Barbell Walking Lunge', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-lunge', 'Dumbbell Lunge', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('leg-extension', 'Leg Extension', 'squat', ARRAY['quads']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'hinge', ARRAY['glutes','posterior']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-glute-bridge', 'Barbell Glute Bridge', 'hinge', ARRAY['glutes','posterior']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('step-up', 'Step-up', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('safety-bar-squat', 'Safety Bar Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('zercher-squat', 'Zercher Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('belt-squat', 'Belt Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('pendulum-squat', 'Pendulum Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('smith-machine-squat', 'Smith Machine Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('heel-elevated-goblet-squat', 'Heel-Elevated Goblet Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-bulgarian-split-squat', 'Dumbbell Bulgarian Split Squat', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('smith-machine-bulgarian-split-squat', 'Smith Machine Bulgarian Split Squat', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-reverse-lunge', 'Barbell Reverse Lunge', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-reverse-lunge', 'Dumbbell Reverse Lunge', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('deficit-reverse-lunge', 'Deficit Reverse Lunge', 'lunge', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('sissy-squat', 'Sissy Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('high-foot-placement-leg-press', 'High Foot Placement Leg Press', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('low-foot-placement-leg-press', 'Low Foot Placement Leg Press', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-landmine-squat', 'Single-Arm Landmine Squat', 'squat', ARRAY['quads','glutes']::text[], 'Quads & Glutes', ARRAY['landmine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('stiff-legged-barbell-deadlift', 'Stiff-Legged Barbell Deadlift', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('lying-leg-curl', 'Lying Leg Curl', 'hinge', ARRAY['posterior']::text[], 'Hamstrings & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-leg-curl', 'Seated Leg Curl', 'hinge', ARRAY['posterior']::text[], 'Hamstrings & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'hinge', ARRAY['posterior']::text[], 'Hamstrings & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('good-morning', 'Good Morning', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('deficit-romanian-deadlift', 'Deficit Romanian Deadlift', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['dumbbell']::text[], ARRAY['DB Romanian Deadlift']::text[], 'strength', 'published', 'custom'),
  ('dumbbell-single-leg-romanian-deadlift', 'Dumbbell Single-Leg Romanian Deadlift', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['dumbbell']::text[], ARRAY['Single-Leg RDL']::text[], 'strength', 'published', 'custom'),
  ('smith-machine-romanian-deadlift', 'Smith Machine Romanian Deadlift', 'hinge', ARRAY['posterior','glutes']::text[], 'Hamstrings & Glutes', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('glute-ham-raise', 'Glute-Ham Raise', 'hinge', ARRAY['posterior']::text[], 'Hamstrings & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'hinge', ARRAY['glutes','posterior']::text[], 'Hamstrings & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('smith-machine-hip-thrust', 'Smith Machine Hip Thrust', 'hinge', ARRAY['glutes','posterior']::text[], 'Hamstrings & Glutes', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-leg-hip-thrust', 'Single-Leg Hip Thrust', 'hinge', ARRAY['glutes','posterior']::text[], 'Hamstrings & Glutes', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-pull-through', 'Cable Pull-Through', 'hinge', ARRAY['glutes','posterior']::text[], 'Hamstrings & Glutes', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-machine-glute-kickback', 'Seated Machine Glute Kickback', 'hinge', ARRAY['glutes']::text[], 'Hamstrings & Glutes', ARRAY['machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-glute-kickback', 'Cable Glute Kickback', 'hinge', ARRAY['glutes']::text[], 'Hamstrings & Glutes', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-hip-abduction', 'Cable Hip Abduction', 'hinge', ARRAY['glutes']::text[], 'Hamstrings & Glutes', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('standing-calf-raise', 'Standing Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-calf-raise', 'Seated Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['machine']::text[], ARRAY['Leg Press Calf Press']::text[], 'strength', 'published', 'custom'),
  ('standing-smith-machine-calf-raise', 'Standing Smith Machine Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['smith machine']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-leg-dumbbell-calf-raise', 'Single-Leg Dumbbell Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('deficit-calf-raise', 'Deficit Calf Raise', 'squat', ARRAY['posterior']::text[], 'Calves', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-curl', 'Barbell Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('ez-bar-curl', 'EZ-Bar Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-biceps-curl', 'Dumbbell Biceps Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hammer-curl', 'Hammer Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('incline-hammer-curl', 'Incline Hammer Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cross-body-hammer-curl', 'Cross-Body Hammer Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('preacher-curl', 'Preacher Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('concentration-curl', 'Concentration Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-biceps-curl', 'Cable Biceps Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('overhead-cable-curl', 'Overhead Cable Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-spider-curl', 'Barbell Spider Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-spider-curl', 'Dumbbell Spider Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-zottman-curl', 'Dumbbell Zottman Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-behind-the-back-curl', 'Cable Behind-the-Back Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-waiter-curl', 'Dumbbell Waiter Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-drag-curl', 'Barbell Drag Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-drag-curl', 'Dumbbell Drag Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('ez-bar-preacher-curl', 'EZ-Bar Preacher Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-preacher-curl', 'Dumbbell Preacher Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-cable-preacher-curl', 'Single-Arm Cable Preacher Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('reverse-grip-barbell-curl', 'Reverse Grip Barbell Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('reverse-grip-ez-bar-curl', 'Reverse Grip EZ-Bar Curl', 'pull', ARRAY['back']::text[], 'Biceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'push', ARRAY['triceps','chest']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('ez-bar-skullcrusher', 'EZ-Bar Skullcrusher', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-ez-bar-skullcrusher', 'Decline EZ-Bar Skullcrusher', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('triceps-dip', 'Triceps Dip', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('bench-dip', 'Bench Dip', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('triceps-pushdown', 'Triceps Pushdown', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('reverse-grip-triceps-pushdown', 'Reverse Grip Triceps Pushdown', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('overhead-dumbbell-triceps-extension', 'Overhead Dumbbell Triceps Extension', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-overhead-triceps-extension', 'Cable Overhead Triceps Extension', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('barbell-floor-press', 'Barbell Floor Press', 'push', ARRAY['triceps','chest']::text[], 'Triceps', ARRAY['barbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('weighted-triceps-dip', 'Weighted Triceps Dip', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('single-arm-cable-triceps-pushdown', 'Single-Arm Cable Triceps Pushdown', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('rope-triceps-pushdown', 'Rope Triceps Pushdown', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('v-bar-triceps-pushdown', 'V-Bar Triceps Pushdown', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-katana-extension', 'Cable Katana Extension', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dumbbell-kickback', 'Dumbbell Kickback', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['dumbbell']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-kickback', 'Cable Kickback', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('jm-press', 'JM Press', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('tate-press', 'Tate Press', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('california-press', 'California Press', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('seated-ez-bar-overhead-triceps-extension', 'Seated EZ-Bar Overhead Triceps Extension', 'push', ARRAY['triceps']::text[], 'Triceps', ARRAY['ez-bar']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-crunch', 'Cable Crunch', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hanging-oblique-knee-raise', 'Hanging Oblique Knee Raise', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('captain-s-chair-leg-raise', 'Captain''s Chair Leg Raise', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-crunch', 'Decline Crunch', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cross-body-crunch', 'Cross-Body Crunch', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('elbow-plank', 'Elbow Plank', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('decline-reverse-crunch', 'Decline Reverse Crunch', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('plate-twist', 'Plate Twist', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['plate']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hanging-toes-to-bar', 'Hanging Toes-to-Bar', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('dragon-flag', 'Dragon Flag', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('rkc-plank', 'RKC Plank', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('from-knees-ab-wheel-rollout', 'From Knees Ab Wheel Rollout', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('from-feet-ab-wheel-rollout', 'From Feet Ab Wheel Rollout', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('pallof-press', 'Pallof Press', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('cable-woodchopper', 'Cable Woodchopper', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['cable']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('weighted-russian-twist', 'Weighted Russian Twist', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom'),
  ('l-sit', 'L-Sit', 'core', ARRAY['posterior']::text[], 'Abs & Core', ARRAY['bodyweight']::text[], '{}'::text[], 'strength', 'published', 'custom')
on conflict ("slug") do nothing;
